return {
    ch4_1_after_lift = {
        {
            id = "ch4.1.after_lift.1",
            style = "charlie",
            text = "重回研究所……升降台落定了。",
            mode = "modal",
        },
        {
            id = "ch4.1.after_lift.2",
            style = "charlie",
            text = "可是这里和外面的城市一样……空荡得令人发慌，看不到任何人的身影。",
            mode = "modal",
        },
    },
    ch4_1_path_observation = {
        {
            id = "ch4.1.path_observation.1",
            style = "researcher",
            speaker = "研究员",
            text = "……异常记录……阿尔吉侬出现认知滞留……多次......停滞",
            mode = "banner",
        },
        {
            id = "ch4.1.path_observation.2",
            style = "researcher",
            speaker = "研究员",
            text = "……尝试重复寻路失败……依然......困在测试结构内……",
            mode = "banner",
        },
        {
            id = "ch4.1.path_observation.3",
            style = "charlie",
            text = "是研究员的声音，听起来像是在隔壁房间做紧急记录。阿尔吉侬被困住了？我得立刻过去！",
            mode = "banner",
        },
    },
    ch4_1_finish = {
        {
            id = "ch4.1.finish.1",
            style = "charlie",
            text = "前面就是通往寻路测试室的门。不论发生了什么，我必须向他问个清楚。",
            mode = "modal",
        },
    },
    ch4_2_intro = {
        {
            id = "ch4.2.intro.1",
            style = "charlie",
            text = "研究员！还有阿尔吉侬……你为什么停在起点？你还好吗？",
            mode = "modal",
        },
        {
            id = "ch4.2.intro.2",
            style = "researcher",
            speaker = "研究员",
            text = "先帮它把道路接通。阿尔吉侬只是连续测试太累了，让它顺着熟悉的路线走完。",
            mode = "modal",
        },
        {
            id = "ch4.2.intro.3",
            style = "charlie",
            text = "只是累了吗……好，我现在就把路拼好。",
            mode = "modal",
        },
    },
    ch4_2_first_pause = {
        {
            id = "ch4.2.first_pause.1",
            style = "charlie",
            text = "阿尔吉侬？这种简单的折角结构……你以前一眼就能看透的。",
            mode = "banner",
        },
    },
    ch4_2_second_pause = {
        {
            id = "ch4.2.second_pause.1",
            style = "charlie",
            text = "它又停下了，眼神里满是迷茫……这绝对不是体力耗尽的眼神！",
            mode = "banner",
        },
        {
            id = "ch4.2.second_pause.2",
            style = "researcher",
            speaker = "研究员",
            text = "别情绪化，查理。这只是偶发的精神疲劳，它需要时间休息。",
            mode = "banner",
        },
        {
            id = "ch4.2.second_pause.3",
            style = "charlie",
            text = "那我就把每一段断路都搭建得清清楚楚！我绝不会让它一个人困在这里。",
            mode = "banner",
        },
    },
    ch4_2_algernon_finish = {
        {
            id = "ch4.2.algernon_finish.1",
            style = "charlie",
            text = "它终于踩上了终点……可曾经那个比我更敏捷的阿尔吉侬，去哪了？",
            mode = "banner",
        },
    },
    ch4_2_finish = {
        {
            id = "ch4.2.finish.1",
            style = "charlie",
            text = "我已经把路全部接通了。别再用“疲劳”搪塞我，阿尔吉侬到底发生了什么？！",
            mode = "modal",
        },
        {
            id = "ch4.2.finish.2",
            style = "researcher",
            speaker = "研究员",
            text = "它现在的波动很复杂。前往前面的训练空间吧，在那里的观察室里我们再谈。",
            mode = "modal",
        },
        {
            id = "ch4.2.finish.3",
            style = "charlie",
            text = "你休想再避开我的问题。我会跟你过去，直到听见真相为止。",
            mode = "modal",
        },
    },
    ch4_3_intro = {
        {
            id = "ch4.3.intro.1",
            style = "charlie",
            text = "我们到了。研究员，现在可以告诉我阿尔吉侬的真实情况了吗？",
            mode = "modal",
        },
        {
            id = "ch4.3.intro.2",
            style = "researcher",
            speaker = "研究员",
            text = "先把这次空间联系测试完成。我们需要它在移动状态下的完整数据，现在下结论还太早。",
            mode = "modal",
        },
        {
            id = "ch4.3.intro.3",
            style = "charlie",
            text = "你总是“下结论太早”……好，我配合你完成测试，但做完之后，你必须正面回答我！",
            mode = "modal",
        },
    },
    ch4_3_observation = {
        {
            id = "ch4.3.observation.1",
            style = "charlie",
            text = "顺便告诉你一件事——我刚才去了研究所外面的城市。那里没有行人、没有车辆，没有任何生活痕迹。",
            mode = "modal",
        },
        {
            id = "ch4.3.observation.2",
            style = "charlie",
            text = "不是那座城毁灭了，而是我感知不到世俗世界的一切。但我却能在这的空间里，清晰地感知到阿尔吉侬的一举一动……",
            mode = "modal",
        },
        {
            id = "ch4.3.observation.3",
            style = "researcher",
            speaker = "研究员",
            text = "……你说什么？你能感知到阿尔吉侬，却感知不到世俗……这种感知剥离，是从什么时候开始的？",
            mode = "modal",
        },
        {
            id = "ch4.3.observation.4",
            style = "charlie",
            text = "从我醒来的那一刻起。不仅如此……刚才我在重构道路时，脑海里竟也隐隐产生了一丝停滞感与眩晕。",
            mode = "modal",
        },
        {
            id = "ch4.3.observation.5",
            style = "researcher",
            speaker = "研究员",
            text = "等等……查理，难道说从你醒来至今……你一直都“看不见”我？！",
            mode = "modal",
        },
    },
    ch4_3_fault = {
        {
            id = "ch4.3.fault.1",
            style = "charlie",
            text = "奇怪……刚刚我对路径的操作……失灵了？",
            mode = "banner",
        },
    },
    ch4_3_pause = {
        {
            id = "ch4.3.pause.1",
            style = "charlie",
            text = "阿尔吉侬又在前方停住了……刚才旋转机关时，我也差点看错方向。",
            mode = "banner",
        },
    },
    ch4_3_algernon_finish = {
        {
            id = "ch4.3.algernon_finish.1",
            style = "charlie",
            text = "它费尽全力走到了终点……它思维里的光芒，正在一点点熄灭。",
            mode = "banner",
        },
    },
    ch4_3_finish = {
        {
            id = "ch4.3.finish.1",
            style = "charlie",
            text = "你一直都在我对面、在房间的角落里看着我，对吗？而我却一直以为你的声音来自墙后的广播……",
            mode = "modal",
        },
        {
            id = "ch4.3.finish.2",
            style = "researcher",
            speaker = "研究员",
            text = "我一直就在这里记录你……比如之前在你刚做完手术时，我就站在终点前等着你，记录着你每一个动作和判断，但我没想到你根本接收不到我的实体。",
            mode = "modal",
        },
        {
            id = "ch4.3.finish.3",
            style = "charlie",
            text = "你早就发现了不对劲，为什么从来不解释？为什么要让我以为自己只是获得了神迹般的空间感知？",
            mode = "modal",
        },
        {
            id = "ch4.3.finish.4",
            style = "researcher",
            speaker = "研究员",
            text = "……我们需要完整的实验数据。跟我回到最初的手术测试室吧，是时候把一切重新对照了。",
            mode = "modal",
        },
        {
            id = "ch4.3.finish.5",
            style = "charlie",
            text = "走吧。......以及刚才操控结构时那种隐隐的迟钝感……我必须搞清楚原因。",
            mode = "modal",
        },
    },
    ch4_4_intro = {
        {
            id = "ch4.4.intro.1",
            style = "researcher",
            speaker = "研究员",
            text = "这里是你刚做完手术、做第一次测试的地方。我们从最初的基因与空间重构记录说起。",
            mode = "modal",
        },
        {
            id = "ch4.4.intro.2",
            style = "researcher",
            speaker = "研究员",
            text = "这场手术重组了你的高阶大脑逻辑，让你获得了洞察空间错位、重构隐秘路径的天赋。",
            mode = "modal",
        },
        {
            id = "ch4.4.intro.3",
            style = "researcher",
            speaker = "研究员",
            text = "但也带来了过载——你的感知屏蔽了所有属于世俗生活的信号。当然……这只是我结合你刚才的描述作出的初步推测。",
            mode = "modal",
        },
        {
            id = "ch4.4.intro.4",
            style = "charlie",
            text = "所以从一开始……世界并没有把我丢下，是我在获得这种能力的同时，永远失去了拥抱世俗的资格。",
            mode = "modal",
        },
    },
    ch4_4_path = {
        {
            id = "ch4.4.path.1",
            style = "researcher",
            speaker = "研究员",
            text = "阿尔吉侬的情况不同。手术初期它很完美，你离开研究所时，它也没有任何衰退征兆。",
            mode = "modal",
        },
        {
            id = "ch4.4.path.2",
            style = "researcher",
            speaker = "研究员",
            text = "但就在你离开后，它的空间认知开始呈断崖式倒退……它开始忘记曾经走过千万次的迷宫。",
            mode = "modal",
        },
        {
            id = "ch4.4.path.3",
            style = "charlie",
            text = "刚才在上一个房间重构路径时，我的手也在发抖，视线里的错视结构开始不受控制……我是不是也在步它的后尘？",
            mode = "modal",
        },
        {
            id = "ch4.4.path.4",
            style = "researcher",
            speaker = "研究员",
            text = "术后即刻剥离世俗感知，以及后续可能出现的结构操纵力衰退……这或许都是手术未知的严重副作用。",
            mode = "modal",
        },
    },
    ch4_4_finish = {
        {
            id = "ch4.4.finish.1",
            style = "charlie",
            text = "在手术前，你们其实警告过我……这条从未有人走过的路，充满了不可预测的危险。",
            mode = "modal",
        },
        {
            id = "ch4.4.finish.2",
            style = "charlie",
            text = "是我太急于摆脱曾经那个笨拙、卑微的自己，是我太渴望能看清这个世界……这是我自己的选择。",
            mode = "modal",
        },
        {
            id = "ch4.4.finish.3",
            style = "researcher",
            speaker = "研究员",
            text = "选择在你，但隐瞒与冷漠是研究所的罪责。这项技术……我们后续不会再研究下去了，所有的项目都会终止。",
            mode = "modal",
        },
        {
            id = "ch4.4.finish.4",
            style = "researcher",
            speaker = "研究员",
            text = "查理，你可以带着阿尔吉侬离开了，你们不必再作为受试者留在这里。",
            mode = "modal",
        },
        {
            id = "ch4.4.finish.5",
            style = "charlie",
            text = "……我的感知......或许终将彻底坠入黑暗，但在那之前，我会陪着阿尔吉侬，一起走完剩下的路。",
            mode = "modal",
        },
    },
}
