return {
    intro = {
        {
            id = "ch1.1.intro.1",
            style = "charlie",
            text = "奇怪……这里是哪里？",
            mode = "modal",
        },
        {
            id = "ch1.1.intro.2",
            style = "charlie",
            text = "我是谁，我怎么会在这里呢……",
            mode = "modal",
        },
        {
            id = "ch1.1.intro.3",
            style = "charlie",
            text = "这整座迷宫……到底是什么地方？",
            mode = "modal",
        },
        {
            id = "ch1.1.intro.4",
            style = "charlie",
            text = "算了，想不起来。那边好像有一扇门，在发光。",
            mode = "modal",
        },
        {
            id = "ch1.1.intro.5",
            style = "charlie",
            text = "也许过去就能离开这儿了。",
            mode = "modal",
        },
    },
    inLevel = {
        {
            id = "ch1.1.in_level.1",
            style = "charlie",
            text = "这里的路，还有这些建筑……我好像在哪见过。",
            mode = "banner",
        },
        {
            id = "ch1.1.in_level.2",
            style = "charlie",
            text = "可脑子里一片空白，什么也记不起。",
            mode = "banner",
        },
        {
            id = "ch1.1.in_level.3",
            style = "charlie",
            text = "算了，门就在前面，先过去再说。",
            mode = "banner",
        },
    },
    clear = {
        {
            id = "ch1.1.clear.1",
            style = "charlie",
            text = "这扇门……好像勾起了一些模糊的印象。",
            mode = "modal",
        },
        {
            id = "ch1.1.clear.2",
            style = "charlie",
            text = "推开看看吧，说不定门后有答案。",
            mode = "modal",
        },
    },
    ch1_2_intro = {
        {
            id = "ch1.2.intro.1",
            style = "charlie",
            text = "门后居然还是这样的建筑？而且前面的路……怎么断开了？",
            mode = "modal",
        },
        {
            id = "ch1.2.intro.2",
            style = "charlie",
            text = "诶，小鼠！",
            mode = "modal",
        },
        {
            id = "ch1.2.intro.3",
            style = "charlie",
            text = "小鼠鼠！我来找你玩玩来咯！",
            mode = "modal",
        },
    },
    ch1_2_mouse = {
        {
            id = "ch1.2.mouse.1",
            style = "charlie",
            text = "别跑啊！诶等等，它是怎么走过去的？！",
            mode = "modal",
        },
        {
            id = "ch1.2.mouse.2",
            style = "charlie",
            text = "那片空中……明明什么都没有啊。",
            mode = "modal",
        },
    },
    ch1_2_researcher = {
        {
            id = "ch1.2.researcher.1",
            style = "researcher",
            speaker = "研究员",
            text = "来吧，往这边走，沿着路过来。",
            mode = "modal",
        },
    },
    ch1_2_clear = {
        {
            id = "ch1.2.clear.1",
            style = "charlie",
            text = "你……是谁？我怎么会在这里？",
            mode = "modal",
        },
        {
            id = "ch1.2.clear.2",
            style = "researcher",
            speaker = "研究员",
            text = "……看来连这也记不得了。你叫查理，而我，只是一名研究员。",
            mode = "modal",
        },
        {
            id = "ch1.2.clear.3",
            style = "researcher",
            speaker = "研究员",
            text = "在这个世界上，绝大多数人都能看清并踏上那些隐秘的认知路径。",
            mode = "modal",
        },
        {
            id = "ch1.2.clear.4",
            style = "researcher",
            speaker = "研究员",
            text = "但你不同。你看不见它们，更无法踏足其上。",
            mode = "modal",
        },
        {
            id = "ch1.2.clear.5",
            style = "researcher",
            speaker = "研究员",
            text = "所以你主动来到研究所找到我，希望能治好这种认知障碍。",
            mode = "modal",
        },
        {
            id = "ch1.2.clear.6",
            style = "researcher",
            speaker = "研究员",
            text = "刚才只是一次测试……看来你的病情比预想中更严重，甚至开始侵蚀记忆了。",
            mode = "modal",
        },
    },
    ch1_3_intro = {
        {
            id = "ch1.3.intro.1",
            style = "charlie",
            text = "怎么又是这样……眼前的路又是断的。",
            mode = "modal",
        },
        {
            id = "ch1.3.intro.2",
            style = "charlie",
            text = "明明刚才那只小老鼠好像走过类似的结构，现在却完全看不出规律……",
            mode = "modal",
        },
        {
            id = "ch1.3.intro.3",
            style = "researcher",
            speaker = "研究员",
            text = "别急。先走到你脚下这条路的尽头——对，就是悬崖边缘。",
            mode = "modal",
        },
    },
    ch1_3_rotate = {
        {
            id = "ch1.3.rotate.1",
            style = "charlie",
            text = "等等……脚下的地面在转动？！",
            mode = "banner",
        },
        {
            id = "ch1.3.rotate.2",
            style = "charlie",
            text = "那边的断口……好像接上了！",
            mode = "banner",
        },
    },
    ch1_3_after_rotate = {
        {
            id = "ch1.3.after_rotate.1",
            style = "researcher",
            speaker = "研究员",
            text = "看到了吗？通路已经建立。现在试着走过来。",
            mode = "modal",
        },
        {
            id = "ch1.3.after_rotate.2",
            style = "charlie",
            text = "好……我试试看。",
            mode = "modal",
        },
    },
    ch1_3_clear = {
        {
            id = "ch1.3.clear.1",
            style = "charlie",
            text = "我刚才……是不是踩在了一条根本不存在的路上？！我的病是不是好了？！",
            mode = "modal",
        },
        {
            id = "ch1.3.clear.2",
            style = "researcher",
            speaker = "研究员",
            text = "很遗憾，并没有。刚才是我在外部强制干预了你的空间认知；一旦离开我的干预，你依然会变回原样。",
            mode = "modal",
        },
        {
            id = "ch1.3.clear.3",
            style = "researcher",
            speaker = "研究员",
            text = "不过……我确实找到了一种彻底根治的方法。",
            mode = "modal",
        },
        {
            id = "ch1.3.clear.4",
            style = "researcher",
            speaker = "研究员",
            text = "刚才那只叫阿尔吉侬的小鼠，你也看见了，它能坦然走过那些“你眼中不存在”的道路。",
            mode = "modal",
        },
        {
            id = "ch1.3.clear.5",
            style = "researcher",
            speaker = "研究员",
            text = "因为它接受了我研发的意识重构手术。手术在它身上非常成功……",
            mode = "modal",
        },
        {
            id = "ch1.3.clear.6",
            style = "researcher",
            speaker = "研究员",
            text = "……但这种手术，还从未在人类身上尝试过。",
            mode = "modal",
        },
        {
            id = "ch1.3.clear.7",
            style = "charlie",
            text = "请让我试试吧！我也想像阿尔吉侬那样……能亲眼看见、亲脚踏上属于我自己的路！",
            mode = "modal",
        },
        {
            id = "ch1.3.clear.8",
            style = "researcher",
            speaker = "研究员",
            text = "这扇门后就是手术室。重构意识的风险完全未知，你真的做好准备了吗？",
            mode = "modal",
        },
        {
            id = "ch1.3.clear.9",
            style = "charlie",
            text = "我准备好了。",
            mode = "modal",
        },
    },
}
